### ISSUE TITLE
"Setup Mabl CLI" action is not working

### ISSUE THREAD

**Issue by omermorad** [mablhq/setup-mabl-cli#20]
I have this step under my CI pipeline in GitHub action:

```
- name: Setup Mabl CLI
  uses: mablhq/setup-mabl-cli@v1
  with:
    workspace: ***********-w
  env:
    MABL_API_KEY: ${{ secrets.MABL_API_KEY }}
```

Then I run this step:

```
- name: Run Mabl Tests
  run:
    mabl tests run \
    --headless \
    --from-plan-id ***********-p \
    --workspace-id ***********-w \
    --mabl-branch ci-e2e \
    --environment-id ***********-e \
    --url http://localhost:8080
```

![image](https://github.com/mablhq/setup-mabl-cli/assets/6696717/4a795def-31ec-449d-a14d-eef64ab14d75)

??

@navehsadeh
